Rails.application.routes.draw do
  get 'orders/new'
  get 'orders/index'
  get 'orders/show'
  get 'orders/create'
  get 'orders/confirm'
  get 'orders/thanks'
  get 'cart_items/index'
  get 'cart_items/create'
  get 'cart_items/update'
  get 'cart_items/destroy'
  get 'cart_items/destroy_all'
  get 'items/index'
  get 'items/show'
  get 'deliveries/index'
  get 'deliveries/create'
  get 'deliveries/edit'
  get 'deliveries/update'
  get 'deliveries/destroy'
  get 'customers/show'
  get 'customers/edit'
  get 'customers/update'
  get 'customers/unsubscribe'
  get 'customers/withdrew'
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
